name: Update SirDNS Status

on:
  workflow_dispatch:

  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update Warhawk status
        run: python scripts/warhawk_status.py

      - name: Commit status.json
        run: |
          git config user.name "SirDNS Bot"
          git config user.email "actions@github.com"
          git add status.json

          if git diff --cached --quiet; then
            echo "Aucune modification."
            exit 0
          fi

          git commit -m "Update SirDNS live status"
          git pull --rebase origin main
          git push origin main
